import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { MuninWriteRejectedError, type MuninClient } from "../src/munin-client.js";
import { createAutonomyProposalReceipt } from "../src/autonomy/proposal-receipts.js";
import { applyRExactProposal, recoverRExactAttempt, type RExactConfigTarget } from "../src/autonomy/r-exact-controller.js";
const h = (s: string) => `sha256:${createHash("sha256").update(s).digest("hex")}`;
const keys = { "hugin-autonomy-proposer": "d".repeat(64) };
const now = () => new Date("2026-07-26T14:00:00.000Z");
class Mem { rows = new Map<string, { content:string; updated_at:string }>(); n=0; async read(ns:string,k:string) { const x=this.rows.get(`${ns}/${k}`); return x ? { ...x, namespace:ns,key:k,found:true } : null; } async write(ns:string,k:string,c:string,_t?:string[], expected?:string,_cl?:string, create?:boolean) { const id=`${ns}/${k}`, old=this.rows.get(id); if(create&&old) throw new MuninWriteRejectedError(ns,k,{error:"conflict",conflict_reason:"already_exists"}); if(expected&&old?.updated_at!==expected) throw new MuninWriteRejectedError(ns,k,{error:"conflict",conflict_reason:"version_mismatch"}); this.rows.set(id,{content:c,updated_at:`v${++this.n}`}); } }
class Target implements RExactConfigTarget { id="hugin-orin-macro-routing"; owner="hugin" as const; axis="macro-routing"; revision="base-1"; digest=h("base"); partial=false; async read(){return {revision:this.revision,digest:this.digest};} async snapshot(){return {ref:"ref:snapshot-330",digest:h("base")};} async replaceExact(base:{revision:string;digest:string}, candidate:string){if(base.digest!==this.digest) throw new Error("cas"); this.digest=this.partial?h("partial"):candidate; this.revision="candidate-1";} async restoreExact(s:{ref:string;digest:string}){this.digest=s.digest;this.revision="base-1";} }
function receipt(){return createAutonomyProposalReceipt({proposalId:"proposal-330-a",experimentRef:"ref:experiment-330",evidenceFingerprints:[h("e")],targetId:"hugin-orin-macro-routing",base:{revision:"base-1",digest:h("base")},candidateContentDigest:h("candidate"),expiresAt:"2026-07-26T15:00:00.000Z",signerKeyId:"hugin-autonomy-proposer"},keys["hugin-autonomy-proposer"]);}
const armed={eligible:true,globalState:"armed" as const,classCoverage:"armed-canary" as const,killSwitchOff:true,watchdogHealthy:true,evidenceFresh:true,uniqueIdentity:true};
describe("R-exact controller",()=>{
 it("persists before mutation and recovers an interruption after mutation to the same committed identity",async()=>{const m=new Mem() as unknown as MuninClient,t=new Target(),r=receipt(); await expect(applyRExactProposal(m,r,keys,t,armed,{now,onPhase:p=>{if(p==="readback")throw new Error("crash");}})).rejects.toThrow("crash"); expect((await recoverRExactAttempt(m,r.proposalId,t,{now})).status).toBe("committed"); expect(t.digest).toBe(r.candidateContentDigest);});
 it("restores the exact snapshot after a partial write",async()=>{const m=new Mem() as unknown as MuninClient,t=new Target();t.partial=true;const r=receipt(); expect((await applyRExactProposal(m,r,keys,t,armed,{now})).status).toBe("reverted"); expect(t.digest).toBe(h("base"));});
 it("refuses default-disarmed and cross-owner application before mutation",async()=>{const m=new Mem() as unknown as MuninClient,t=new Target(),r=receipt(); await expect(applyRExactProposal(m,r,keys,t,undefined,{now})).rejects.toThrow("admission"); const cross=createAutonomyProposalReceipt({...{proposalId:"proposal-330-b",experimentRef:"ref:experiment-330",evidenceFingerprints:[h("e")],base:{revision:"base-1",digest:h("base")},candidateContentDigest:h("candidate"),expiresAt:"2026-07-26T15:00:00.000Z",signerKeyId:"hugin-autonomy-proposer"},targetId:"gille-micro-routing"},keys["hugin-autonomy-proposer"]); await expect(applyRExactProposal(m,cross,keys,t,armed,{now})).rejects.toThrow(); expect(t.digest).toBe(h("base"));});
});
