import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  buildExample,
  examplesToJsonl,
  parseJsonl,
  pii,
  validateExample,
} from "../../src/privacy-filter/fixtures.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIX = join(HERE, "..", "..", "eval", "privacy-filter", "fixtures");

describe("fixtures authoring", () => {
  it("computes offsets by construction so spans slice to their surface", () => {
    const ex = buildExample("t1", [
      "Hi ",
      pii("private_person", "Sarah Whitlock"),
      ", call ",
      pii("private_phone", "(415) 555-0173"),
      ".",
    ]);
    expect(ex.text).toBe("Hi Sarah Whitlock, call (415) 555-0173.");
    expect(validateExample(ex)).toEqual([]);
    const person = ex.spans.find((s) => s.label === "private_person")!;
    expect(ex.text.slice(person.start, person.end)).toBe("Sarah Whitlock");
  });

  it("round-trips through JSONL serialization", () => {
    const ex = buildExample(
      "t2",
      ["pay ", pii("account_number", "5402-1183"), " by ", pii("private_date", "2026-06-30")],
      { lang: "sv", category: "invoice" },
    );
    const [parsed] = parseJsonl(examplesToJsonl([ex]));
    expect(parsed.text).toBe(ex.text);
    expect(parsed.info.lang).toBe("sv");
    expect(parsed.info.category).toBe("invoice");
    expect(parsed.spans.map((s) => [s.label, s.start, s.end])).toEqual(
      ex.spans.map((s) => [s.label, s.start, s.end]),
    );
  });

  it("validateExample catches an out-of-bounds or mismatched span", () => {
    const bad = buildExample("t3", ["ok"]);
    bad.spans.push({ label: "secret", start: 0, end: 99, text: "nope" });
    expect(validateExample(bad).length).toBe(1);
  });

  it("merges recurring identical surfaces into one key with multiple offsets", () => {
    const ex = buildExample("t4", [
      pii("private_person", "Bo"),
      " and ",
      pii("private_person", "Bo"),
      " again",
    ]);
    const jsonl = examplesToJsonl([ex]);
    const obj = JSON.parse(jsonl.trim());
    expect(obj.spans["private_person: Bo"]).toHaveLength(2);
  });
});

// These run only when the committed fixtures exist (generated by
// `npm run build:pii-fixtures`). They are the defense-in-depth gate that the
// shipped fixtures are internally consistent.
describe("committed fixtures", () => {
  const piiPath = join(FIX, "grimnir-pii.jsonl");
  const cleanPath = join(FIX, "clean-technical.jsonl");
  const ready = existsSync(piiPath) && existsSync(cleanPath);

  it.runIf(ready)("every labelled span slices to its surface text", () => {
    const examples = parseJsonl(readFileSync(piiPath, "utf8"));
    expect(examples.length).toBeGreaterThan(0);
    const issues = examples.flatMap(validateExample);
    expect(issues).toEqual([]);
  });

  it.runIf(ready)("clean fixtures carry zero spans", () => {
    const clean = parseJsonl(readFileSync(cleanPath, "utf8"));
    expect(clean.length).toBeGreaterThan(0);
    for (const ex of clean) expect(ex.spans).toEqual([]);
  });

  it.runIf(ready)("labelled fixtures cover all 8 OPF labels", () => {
    const examples = parseJsonl(readFileSync(piiPath, "utf8"));
    const seen = new Set(examples.flatMap((e) => e.spans.map((s) => s.label)));
    for (const label of [
      "private_person",
      "private_email",
      "private_phone",
      "private_address",
      "private_date",
      "private_url",
      "account_number",
      "secret",
    ]) {
      expect(seen.has(label as never)).toBe(true);
    }
  });
});
